# Generated by Django 4.2.5 on 2024-04-05 05:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ShoppingCart", "0003_alter_cart_user"),
        ("Order", "0003_alter_order_user"),
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
