# Generated by Django 5.0.2 on 2024-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('createTime', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
