# Generated by Django 5.0.2 on 2024-04-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
