# Generated by Django 5.0.2 on 2024-04-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(default='Clothing', max_length=32),
            preserve_default=False,
        ),
    ]
