# Generated by Django 5.0.2 on 2024-04-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopPage', '0002_product_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
